site_name: ACE - Architect
theme:
  name: "material"
  palette:
    primary: orange
  feature:
    tabs: true
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - admonition
  - footnotes
  - tables
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      # linenums: true # https://squidfunk.github.io/mkdocs-material/extensions/codehilite/#highlighting-specific-lines
      guess_lang: true
  # - pymdownx.highlight:
  #     css_class: codehilite
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.tilde
plugins:
  - pdf-export:
      verbose: true
      enabled_if_env: ENABLE_PDF_EXPORT
  - search
  - awesome-pages:
      filename: .title
extra_css:
  - "css/pdf.css"
  - "css/styles.css"
