# Project information
site_name: ACE - Architect

# Configuration
theme:
  name: material
  favicon: "img/favicon.ico"
  # logo: "img/favicon.ico"
  palette:
    primary: teal
    accent: orange
  feature:
    tabs: true
  font:
    text: Roboto
    code: Roboto Mono

# Customization
extra:
  social:
    - type: "facebook"
      link: "https://www.facebook.com/BusinessImagingSystems"
    - type: "linkedin"
      link: "https://www.linkedin.com/company/business-imaging-systems"
    - type: "twitter"
      link: "https://twitter.com/grooper_ai"
    - type: "youtube"
      link: "https://www.youtube.com/channel/UCiJPKqS_enHrFsX49cngqag"

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - tables
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.escapeall
  - codehilite:
      # linenums: true # https://squidfunk.github.io/mkdocs-material/extensions/codehilite/#highlighting-specific-lines
      guess_lang: true
  # - pymdownx.highlight:
  #     css_class: codehilite
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: true

# pages:
#   - Home: index.md
#   - vol-1: vol-1/acquire.md
#   - vol-1: vol-1/condition.md
# - vol-1: vol-1/organize.md
# - vol-1: vol-1/collect.md
# - vol-1: vol-1/deliver.md
# - vol-2: vol-2/acquire.md
# - vol-2: vol-2/condition.md
# - vol-2: vol-2/organize.md
# - vol-2: vol-2/collect.md
# - vol-2: vol-2/deliver.md

plugins:
  - pdf-export:
      verbose: true
      enabled_if_env: ENABLE_PDF_EXPORT
  - search
  - awesome-pages:
      filename: .title
extra_css:
  - "assets/css/glightbox.min.css"
  - "assets/css/pdf.css"
  - "assets/css/styles.css"
extra_javascript:
  - "assets/js/glightbox.min.js"
  - "assets/js/jquery-3.3.1.min.js"
  - "assets/js/app.js"
