site_name: ACE - Architect
theme:
  name: "material"
  palette:
    primary: orange
  feature:
    tabs: true
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.tilde
plugins:
  - pdf-export:
      verbose: true
      enabled_if_env: ENABLE_PDF_EXPORT
  - search
  - awesome-pages:
      filename: .title
extra_css:
  - "css/pdf.css"
  - "css/styles.css"
