# Project information
site_name: ACE - Architect

# Configuration
theme:
  name: material
  custom_dir: custom_theme
  favicon: "img/favicon.ico"
  # logo: "img/favicon.ico"
  palette:
    primary: teal
    accent: orange
  feature:
    tabs: true
  font:
    text: Roboto
    code: Roboto Mono

# Customization
extra:
  social:
    - type: "facebook"
      link: "https://www.facebook.com/BusinessImagingSystems"
    - type: "linkedin"
      link: "https://www.linkedin.com/company/business-imaging-systems"
    - type: "twitter"
      link: "https://twitter.com/grooper_ai"
    - type: "youtube"
      link: "https://www.youtube.com/channel/UCiJPKqS_enHrFsX49cngqag"

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - tables
  # - pymdownx.b64:
  #     base_path: docs
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.escapeall
  - codehilite:
      # linenums: true # https://squidfunk.github.io/mkdocs-material/extensions/codehilite/#highlighting-specific-lines
      guess_lang: true
  # - pymdownx.highlight:
  #     css_class: codehilite
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: true
plugins:
  # - pdf-export:
  #     verbose: true
  # enabled_if_env: ENABLE_PDF_EXPORT
  - search
  - awesome-pages:
      filename: .title
extra_css:
  - "css/pdf.css"
  - "css/styles.css"
  # - "custom_theme/css/glightbox.css"
  # - "css/nobg.css"
extra_javascript:
  #   - "custom_theme/js/glightbox.js"
  # - "js/regex-colorizer.js"
  # - "js/app.js"
